[package]
name = "payground-open"
version = "0.1.0"
edition = "2021"

[dependencies]
thiserror = "2.0.11"
thiserror-impl = "2.0.11"
cubecl = { version = "0.4.0", features = [
    "wgpu",
    "reduce",
] }
rand = "0.8.5"